import { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css';

import { ThirdwebClientProvider } from '@/components/ThirdwebClientProvider';
// import dynamic from 'next/dynamic';
import QueryProvider from "@/components/QueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

// const QueryProvider = dynamic(() => import('@/components/QueryClientProvider'), { ssr: false });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <QueryProvider>
          <ThirdwebClientProvider>
            {children}
          </ThirdwebClientProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
